#!/bin/ksh

daemon="/usr/local/sbin/gateholdd serve-read-only"
daemon_logger="daemon.info"

. /etc/rc.d/rc.subr

pexp="/usr/local/sbin/gateholdd serve-read-only"
rc_bg=YES
rc_reload=NO

rc_configtest() {
	rc_exec "/usr/local/sbin/gateholdd check-config ${daemon_flags}"
}

rc_cmd $1
