#include "gatehold/firewall/pf_renderer.hpp"
#include "test_support.hpp"

#include <string>
#include <utility>

namespace firewall = sasd::gatehold::firewall;

namespace {

firewall::RuleSet example_ruleset() {
    firewall::Rule enabled{
        .id = "allow-lan-https",
        .description = "Allow HTTPS",
        .action = firewall::Action::pass,
        .direction = firewall::Direction::inbound,
        .address_family = firewall::AddressFamily::inet,
        .interface = "em1",
        .protocol = firewall::Protocol::tcp,
        .source = firewall::Endpoint{.network = "192.0.2.0/24"},
        .destination = firewall::Endpoint{.network = "any", .port = 443},
        .log = true,
        .quick = true,
        .enabled = true};

    firewall::Rule disabled{
        .id = "disabled-example",
        .description = "Not active",
        .action = firewall::Action::block,
        .direction = firewall::Direction::outbound,
        .address_family = firewall::AddressFamily::inet6,
        .interface = "em2",
        .protocol = firewall::Protocol::udp,
        .source = firewall::Endpoint{.network = "any"},
        .destination = firewall::Endpoint{.network = "2001:db8::/32", .port = 53},
        .log = true,
        .quick = true,
        .enabled = false};

    return firewall::RuleSet{
        .revision = 7, .rules = {std::move(enabled), std::move(disabled)}};
}

}  // namespace

int main() {
    gatehold::test::Context test;
    const firewall::PfRenderer renderer;

    const auto rendered = renderer.render(example_ruleset());
    test.check(rendered.ok(), "valid ruleset renders successfully");
    const std::string expected{
        "# Generated by SASD Gatehold. DO NOT EDIT.\n"
        "# Configuration revision: 7\n\n"
        "set block-policy drop\n"
        "set skip on lo\n\n"
        "block log all\n\n"
        "# rule allow-lan-https: Allow HTTPS\n"
        "pass in log quick on em1 inet proto tcp from 192.0.2.0/24 to any port 443 keep state\n\n"
        "# disabled rule disabled-example\n"};
    test.check(rendered.ruleset == expected, "PF output matches the golden ruleset");
    test.check(
        rendered.ruleset.find("2001:db8::/32") == std::string::npos,
        "disabled rule does not become active PF syntax");

    auto unsafe = example_ruleset();
    unsafe.rules.front().interface = "em0\npass all";
    const auto rejected = renderer.render(unsafe);
    test.check(!rejected.ok(), "unsafe ruleset is rejected");
    test.check(rejected.ruleset.empty(), "rejected ruleset emits no partial output");

    return test.result();
}
