#include "gatehold/firewall/pf_renderer.hpp"

#include <sstream>
#include <string_view>

namespace sasd::gatehold::firewall {
namespace {

void append_token(std::ostringstream& output, std::string_view value) {
    if (!value.empty()) {
        output << ' ' << value;
    }
}

void append_endpoint(
    std::ostringstream& output,
    std::string_view keyword,
    const Endpoint& endpoint) {
    output << ' ' << keyword << ' ' << endpoint.network;
    if (endpoint.port.has_value()) {
        output << " port " << *endpoint.port;
    }
}

void append_rule(std::ostringstream& output, const Rule& rule) {
    output << "\n# rule " << rule.id;
    if (!rule.description.empty()) {
        output << ": " << rule.description;
    }
    output << '\n' << to_string(rule.action);
    append_token(output, to_string(rule.direction));

    if (rule.log) {
        output << " log";
    }
    if (rule.quick) {
        output << " quick";
    }
    if (!rule.interface.empty()) {
        output << " on " << rule.interface;
    }

    append_token(output, to_string(rule.address_family));
    if (rule.protocol != Protocol::any) {
        output << " proto " << to_string(rule.protocol);
    }

    append_endpoint(output, "from", rule.source);
    append_endpoint(output, "to", rule.destination);

    if (rule.action == Action::pass) {
        output << " keep state";
    }
    output << '\n';
}

}  // namespace

bool RenderResult::ok() const noexcept {
    return validation.ok();
}

RenderResult PfRenderer::render(const RuleSet& rule_set) const {
    RenderResult result;
    result.validation = validate(rule_set);
    if (!result.validation.ok()) {
        return result;
    }

    std::ostringstream output;
    output << "# Generated by SASD Gatehold. DO NOT EDIT.\n"
           << "# Configuration revision: " << rule_set.revision << "\n\n"
           << "set block-policy drop\n"
           << "set skip on lo\n\n"
           << "block log all\n";

    for (const auto& rule : rule_set.rules) {
        if (rule.enabled) {
            append_rule(output, rule);
        } else {
            output << "\n# disabled rule " << rule.id << '\n';
        }
    }

    result.ruleset = output.str();
    return result;
}

}  // namespace sasd::gatehold::firewall

